import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, RefreshControl, StyleSheet, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { Bell, ChevronLeft, ChevronRight, Circle, X } from "lucide-react-native";

import { Typography, Card, BrandWordmark } from "@/components/ui";
import { TOKENS } from "@/constants/tokens";
import { useAppTheme } from "@/contexts/ThemeContext";
import { useNotifications } from "@/hooks/useNotifications";
import type { AppNotification } from "@/services/notification.service";
import { routeNotification } from "@/utils/notification-routing";

type ViewFilter = "all" | "unread" | "orders" | "messages" | "system";
type Row = { kind: "header"; id: string; title: string } | { kind: "notification"; item: AppNotification };
const LABELS: Record<string, string> = { new_order: "طلب جديد", order_status: "حالة الطلب", status_change: "تحديث الحالة", payment: "دفعة", settlement: "تسوية", message: "رسالة", chat: "رسالة", system: "النظام" };
const typeOf = (item: AppNotification) => (item.notification_type || item.type || "system").toLowerCase();
const isUnread = (item: AppNotification) => !item.is_read && !item.read_at;
function matches(item: AppNotification, filter: ViewFilter) { const type = typeOf(item); if (filter === "unread") return isUnread(item); if (filter === "orders") return /order|delivery|assign/.test(type); if (filter === "messages") return /message|chat/.test(type); if (filter === "system") return /system|payment|settlement/.test(type); return true; }
function groupFor(date: string) { const now = new Date(); const value = new Date(date); const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime(); const valueStart = new Date(value.getFullYear(), value.getMonth(), value.getDate()).getTime(); const days = Math.round((start - valueStart) / 86400000); return days === 0 ? "اليوم" : days === 1 ? "أمس" : value.toLocaleDateString("ar-DZ", { day: "numeric", month: "long" }); }

export default function CustomerNotificationsScreen() {
  const router = useRouter(); const { colors, isRTL: rtl } = useAppTheme(); const [filter, setFilter] = useState<ViewFilter>("all");
  const { notifications, loading, refreshing, unreadCount, refresh, markRead, markAllRead, remove } = useNotifications(filter === "unread" ? "unread" : "all");
  const visible = useMemo(() => notifications.filter((item) => matches(item, filter)), [notifications, filter]);
  const rows = useMemo<Row[]>(() => { const result: Row[] = []; let last = ""; visible.forEach((item) => { const group = groupFor(item.created_at); if (group !== last) { result.push({ kind: "header", id: `group-${group}`, title: group }); last = group; } result.push({ kind: "notification", item }); }); return result; }, [visible]);
  const open = async (item: AppNotification) => { if (isUnread(item)) await markRead(item.id); routeNotification(router, item, "customer"); };
  const renderRow = ({ item: row }: { item: Row }) => { if (row.kind === "header") return <Typography variant="caption" color="secondary" style={styles.groupHeader}>{row.title}</Typography>; const item = row.item; const unread = isUnread(item); const type = typeOf(item); const label = LABELS[type] || type; return <TouchableOpacity onPress={() => void open(item)} activeOpacity={0.78} style={styles.itemSpacing}><Card style={unread ? { borderColor: `${colors.primary}55`, backgroundColor: colors.bgElevated } : undefined}><View style={[styles.notificationRow, { flexDirection: rtl ? "row-reverse" : "row" }]}><View style={[styles.iconWrapper, { backgroundColor: unread ? `${colors.primary}18` : colors.bgElevated }]}><Bell size={20} color={unread ? colors.primary : colors.textDisabled} /></View><View style={[styles.notificationInfo, { alignItems: rtl ? "flex-end" : "flex-start" }]}><View style={[styles.titleRow, { flexDirection: rtl ? "row-reverse" : "row" }]}><Typography variant="h3" numberOfLines={1} style={unread ? { fontWeight: "700" } : {}}>{item.title || label}</Typography><View style={styles.actions}>{unread && <Circle size={8} color={colors.primary} fill={colors.primary} />}<TouchableOpacity onPress={() => Alert.alert("حذف التنبيه", "هل أنت متأكد من حذف هذا التنبيه؟", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => void remove(item.id) }])} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}><X size={16} color={colors.textDisabled} /></TouchableOpacity></View></View>{item.body && <Typography variant="body" color="secondary" numberOfLines={2}>{item.body}</Typography>}<View style={[styles.metaRow, { flexDirection: rtl ? "row-reverse" : "row" }]}><Typography variant="caption" color="disabled">{new Date(item.created_at).toLocaleString("ar-DZ")}</Typography><Typography variant="caption" color="disabled">{label}</Typography></View></View></View></Card></TouchableOpacity>; };
  if (loading && !refreshing) return <View style={[styles.centered, { backgroundColor: colors.bgBase }]}><ActivityIndicator size="large" color={colors.primary} /></View>;
  const filters: Array<[ViewFilter, string]> = [["all", "الكل"], ["unread", `غير مقروء (${unreadCount})`], ["orders", "الطلبات"], ["messages", "الرسائل"], ["system", "النظام"]];
  return <SafeAreaView style={[styles.safeArea, { backgroundColor: colors.bgBase }]} edges={["top"]}><View style={[styles.header, { flexDirection: rtl ? "row-reverse" : "row" }]}><TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>{rtl ? <ChevronRight size={24} color={colors.textPrimary} /> : <ChevronLeft size={24} color={colors.textPrimary} />}</TouchableOpacity><Typography variant="h1" style={styles.headerTitle}>مركز الإشعارات</Typography><BrandWordmark size="compact" style={styles.headerLogo} /></View><View style={styles.toolbar}><FlatList horizontal inverted={rtl} showsHorizontalScrollIndicator={false} data={filters} keyExtractor={([key]) => key} renderItem={({ item: [key, label] }) => <TouchableOpacity onPress={() => setFilter(key)} style={[styles.filterChip, { backgroundColor: filter === key ? colors.primary : colors.bgSurface, borderColor: filter === key ? colors.primary : colors.borderSubtle }]}><Typography variant="caption" style={{ color: filter === key ? "#FFF" : colors.textSecondary, fontWeight: filter === key ? "700" : "500" }}>{label}</Typography></TouchableOpacity>} contentContainerStyle={styles.filterList} />{unreadCount > 0 && <TouchableOpacity onPress={() => void markAllRead()}><Typography variant="caption" color="primary" style={styles.markAll}>تحديد الكل كمقروء</Typography></TouchableOpacity>}</View><FlatList data={rows} renderItem={renderRow} keyExtractor={(row) => row.kind === "header" ? row.id : row.item.id} contentContainerStyle={styles.listContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void refresh(true)} colors={[colors.primary]} />} ListEmptyComponent={<View style={styles.emptyContainer}><Bell color={colors.textDisabled} size={56} /><Typography variant="h3" color="secondary" style={styles.emptyText}>لا توجد إشعارات في هذا القسم</Typography></View>} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1 }, centered: { flex: 1, justifyContent: "center", alignItems: "center" }, header: { padding: TOKENS.spacing.lg, paddingTop: TOKENS.spacing.md, alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "rgba(0,0,0,0.05)" }, headerLogo: { flexShrink: 0 }, headerTitle: { color: TOKENS.colors.brandPrimary, flex: 1, textAlign: "center" }, backBtn: { padding: 4 }, toolbar: { paddingVertical: TOKENS.spacing.sm }, filterList: { paddingHorizontal: TOKENS.spacing.lg, gap: TOKENS.spacing.sm }, filterChip: { paddingHorizontal: TOKENS.spacing.md, paddingVertical: TOKENS.spacing.sm, borderRadius: TOKENS.radius.full, borderWidth: 1 }, markAll: { textAlign: "right", paddingHorizontal: TOKENS.spacing.lg, paddingTop: TOKENS.spacing.sm, fontWeight: "700" }, listContent: { padding: TOKENS.spacing.lg, paddingTop: TOKENS.spacing.sm, flexGrow: 1 }, groupHeader: { textAlign: "right", fontWeight: "700", marginTop: TOKENS.spacing.sm, marginBottom: TOKENS.spacing.xs }, itemSpacing: { marginBottom: TOKENS.spacing.sm }, notificationRow: { alignItems: "flex-start", gap: TOKENS.spacing.md }, iconWrapper: { width: 44, height: 44, borderRadius: 22, justifyContent: "center", alignItems: "center" }, notificationInfo: { flex: 1 }, titleRow: { alignItems: "center", gap: 8, marginBottom: 2, justifyContent: "space-between", width: "100%" }, actions: { flexDirection: "row", alignItems: "center", gap: 8 }, metaRow: { alignItems: "center", justifyContent: "space-between", marginTop: TOKENS.spacing.xs, width: "100%" }, emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center", paddingTop: 100 }, emptyText: { marginTop: 16 } });
