import { normalizeHeroSlide } from "../src/components/market/hero/hero.utils";
import { productToHero, promotionToHero, resolveSmartHeroSlides, storeToHero } from "../src/components/market/hero/hero.smart";
import { getHeroAutoplayInterval, nextHeroIndex } from "../src/components/market/hero/hero.autoplay";

let passed = 0; let failed = 0;
const assert = (value: unknown, label: string) => { if (value) { passed++; console.log(`✅ ${label}`); } else { failed++; console.log(`❌ ${label}`); } };
const image = "https://cdn.example.test/hero.jpg";
const store = storeToHero({ id: "store-1", name: "متجر جديد", cover_url: image, created_at: "2026-09-09T00:00:00Z", status: "active" }, "new_store")!;
const featured = storeToHero({ id: "store-2", name: "متجر مميز", cover_url: image, created_at: "2026-09-09T00:00:00Z", status: "active", is_featured: true }, "featured_store")!;
const product = productToHero({ id: "product-1", store_id: "store-1", name: "منتج", image_url: image, created_at: "2026-09-09T00:00:00Z", status: "active", is_available: true })!;
const promotion = promotionToHero({ id: "promo-1", store_id: "store-1", title: "عرض", image_url: image, discount_type: "percentage", discount_value: 20, starts_at: "2026-09-08T00:00:00Z", ends_at: "2026-09-10T00:00:00Z", is_active: true, created_at: "2026-09-09T00:00:00Z", stores: { name: "متجر جديد", status: "active" } }, Date.parse("2026-09-09T12:00:00Z"))!;
const manual = { ...store, id: "manual-1", entityId: "store-2", source: "manual" as const, title: "Override", pinToTop: true };
const resolved = resolveSmartHeroSlides({ manual: [manual], promotions: [promotion], featuredStores: [featured, store], newStores: [store], products: [product] });
assert(resolved[0].source === "manual", "manual override has highest priority");
assert(resolved[1].source === "promotion", "promotion precedes featured stores");
assert(getHeroAutoplayInterval() === 3000, "default slide duration is 3 seconds");
assert(getHeroAutoplayInterval(8) === 8000, "founder slide duration controls autoplay");
assert(nextHeroIndex(4, 5) === 0 && nextHeroIndex(0, 5) === 1, "autoplay follows resolver order and wraps");
assert(resolved.filter((slide) => slide.entityId === "store-1").length === 1, "duplicate entities are removed");
assert(resolved.some((slide) => slide.source === "product"), "available products are a source");
assert(promotionToHero({ ...promotion as any, ends_at: "2026-09-01T00:00:00Z" }) === null, "expired promotions are excluded");
assert(storeToHero({ ...store as any, status: "paused" }, "new_store") === null, "inactive stores are excluded");
assert(productToHero({ ...product as any, is_available: false }) === null, "unavailable products are excluded");
assert(normalizeHeroSlide({ id: "manual", content_type: "custom", source: "FOUNDER", image_url: image, is_active: true }).source === "manual", "manual source is debug-visible");
console.log(`Smart Hero tests: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
